// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvpgcinzlplsrqnigdch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2cGdjaW56bHBsc3JxbmlnZGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Mzg2NzQsImV4cCI6MjA1OTMxNDY3NH0.catqv65IF-Rjp_ECb735Gp8iKvdC6rfhi60fgRB-0sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);